[package]
name = "plint"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.6.7", features = ["derive"] }
dirs = "7.0.0"
inquire = "0.9.4"
open = "5.4.4"
owo-colors = "4.4.0"
plint-linter = { workspace = true }
serde = "1.0.229"
unicode-width = "0.2.2"
url = "2.5.8"
yaml_serde = "0.10.7"
